### ISSUE TITLE
feature: edit script

### ISSUE THREAD

**Issue by kicsiede** [Turnerj/Quickenshtein#68]
hello,

is there a chance you consider making a way to obtain an edit script (actual insertions/deletions/substitutions) for the shortest distance?  (actual insertions/deletions/substitutions)

thanks,

**Comment by Turnerj** [comment]
Before I wrote Quickenshtein, I had an implementation provide details about the shortest distance like the insertions/deletions/substitutions however it is pretty slow and memory inefficient.

Part of the problem is that many performance improvements are thrown out when doing so. You must keep the whole virtual "table" of values in memory to return the shortest path.

You can check some of the implementations I tried [here](https://github.com/Turnerj/TextDifferenceBenchmarking) however I don't provide any support for the code there.

Maybe in the future I'll revisit it again as an extension to Quickenshtein however with the complexity of the Quickenshtein codebase, it is unlikely that I will.
